### ISSUE TITLE
"Runs" parameter being incorrectly taken not as an unsigned number

### ISSUE THREAD

**Issue by gpetraglia** [rsksmart/rsk-contract-verifier#1]
Hi, I'm trying to verify a contract's code in the explorer of the mainnet(explorer.rsk.co) but I'm having issues with it.
The contract was compiled with the optimization enabled and with the parameter "runs" set to 1.
The verifier tells me, as expected, the verification failed if I set the "runs" parameter to 200, for example. The actual issue happens when I try to change the optimizations "runs" parameter to 1, after that if I submit the form the explorer tells me that 'The "runs" setting must be an unsigned number.'
This keeps happening even if I change the runs parameter back to the default value(200)
However, if I refresh the page the error doesn't appear again until I try to set the runs parameter to 1.

**Comment by emiliorizzo** [comment]
Hi @gpetraglia. thanks for your report.
The issue was fixed by 50f53c6.
